version: '3'
name: inventory-prisma-db
services:
  # api:
  #   container_name: inventory-api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/app/
  #     - /app/node_modules
  #   ports:
  #     - 3000:3000
  #   environment:
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_NAME: ${DB_NAME}
  #     # DB_HOST: ${DB_HOST}
  #     DB_HOST: inventoryDB
  #     DB_PORT: ${DB_PORT}
  #     DB_USERNAME: ${DB_USERNAME}
  #     JWT_SECRET: ${JWT_SECRET}
  #   depends_on:
  #     - db
  db:
    container_name: inventoryDB
    image: postgres:16.6
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db-data:/var/lib/postgresql/data

volumes:
  db-data:
    external: false
